theme: jekyll-theme-slate
title: Dinesh N
description: Data Analyst. <br> Tools: SQL Server, MySQL, MS Excel, PowerBI, Tableau etc. <br> Skills: Data Analysis, Visualisation, Dashboards and Reporting
