theme: jekyll-theme-slate
title: Dinesh N
description: Data Analyst. 
navbar-links:
  About Me: "aboutme"
  Projects:
    - SQL: "https://beautifuljekyll.com"
    - Excel: "https://www.markdowntutorial.com/"
    - Power BI: 
